spring.application.name=stock

server.port=${PORT:10000}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:stockdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
