spring.datasource.url=${jdbc:postgresql://dpg-d8bgerdokfvc73d0iiv0-a:5432/testdb_t7uh}
spring.datasource.username=${testdb_user}
spring.datasource.password=${XhS8vrpb6tK6IC7HurThYqd554QXRRq0}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=${PORT:10000}