spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d8bgerdokfvc73d0iiv0-a:5432/testdb_t7uh?}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:testdb_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:XhS8vrpb6tK6IC7HurThYqd554QXRRq0}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=${PORT:8080}
server.address=0.0.0.0
spring.jpa.open-in-view=false