spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ep-rapid-truth-apf159ur-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_ZGDCh25WAPNV}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=${PORT:8080}
server.address=0.0.0.0
spring.jpa.open-in-view=false
server.error.whitelabel.enabled=false